 
version: '3.3'

services:
  app:
    build: .
    image: adv-concepts:latest
    command: node index.js
    restart: always
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports: 
      - "3000:3000"
